Article_Crud/CRUDEASYMODE/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogv1/', include('blogv1.urls')),
]

Article_Crud/blogv1/urls.py
from django.urls import path
from . import views

app_name = 'blogv1'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

Article_Crud/blogv1/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 최근 글 순서로 정렬하기
    # class Meta(modles.Meta):
        

Article_Crud/blogv1/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'blogv1/index.html', context)


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        article = Article.objects.create(
            title=title,
            content=content
        )
        return redirect('blogv1:index')
    else:
        return render(request, 'blogv1/create.html')

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'blogv1/detail.html', context)

def delete(request, pk):
    Article.objects.get(pk=pk).delete()
    return redirect('blogv1:index')

def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        context = {
            'article' : article
        }
        return render(request, 'blogv1/detail.html', context)
    else:
        context = {
            'article' : article
        }
        return render(request, 'blogv1/update.html', context)

Article_Crud/blogv1/templates/blogv1/create.html
{% extends 'base.html' %}

{% block body %}
<h1>글쓰기</h1>
<form action="{% url 'blogv1:create' %}" method="POST">
  {% csrf_token %}
  <p>제목:<input type="text" name="title" placeholder="제목을 입력해주세요"></p>
  <p>내용:<textarea name="content" cols="30" rows="10" placeholder="내용을 입력해주세요"></textarea></p>
  <input type="submit">
</form>

{% endblock %}

Article_Crud/blogv1/templates/blogv1/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>상세보기</h1>
<p>제목 : {{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
<p>작성날짜 : {{ article.created_at}} | 수정날짜 : {{ article.updated_at }} </p>

<p><a href="{% url 'blogv1:update' article.pk %}">[수정하기]</a> | <a href="{% url 'blogv1:delete' article.pk %}">[삭제하기]</a></p>
{% endblock %}

Article_Crud/blogv1/templates/blogv1/index.html
{% extends 'base.html' %}

{% block body %}
<h1>Blog Articles</h1>

<ol>
{% for article in articles %}
  <li>
    <a href="{% url 'blogv1:detail' article.pk %}">{{article.title}}</a>
  </li>
{% endfor %}
</ol>

<a href="{% url 'blogv1:create' %}">새글쓰기</a>

{% endblock %}

Article_Crud/blogv1/templates/blogv1/update.html
{% extends 'base.html' %}

{% block body %}
<h1>수정하기</h1>
<form action="{% url 'blogv1:update' article.pk %}" method="POST">
  {% csrf_token %}
  <p>제목:<input type="text" name="title" value="{{ article.title }}"></p>
  <p>내용:<textarea name="content" cols="30" rows="10">{{ article.content }}</textarea></p>
  <input type="submit">
</form>

{% endblock %}