Comment_Crud/BOARDEASY/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]

Comment_Crud/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/update', views.update, name="update"),
    path('<int:article_pk>/delete', views.delete, name="delete"),
    path('<int:article_pk>/comment_create/', views.comment_create, name="comment_create"),
    path('<int:article_pk>/<int:comment_pk>/comment_delete/', views.comment_delete, name="comment_delete"),
    path('<int:article_pk>/<int:comment_pk>/comment_update/', views.comment_update, name="comment_update"),
]

Comment_Crud/board/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=True)

Comment_Crud/board/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
# Create your views here.

# 인덱스 함수
def index(request):
    articles = Article.objects.all()
    context = {
        "articles" : articles,
    }
    if request.session.get("comment_pk"):
        del request.session["comment_pk"]
    return render(request, 'board/index.html', context)

# 게시글 작성 함수
def create(request):
    if request.method == "POST":
        article = Article.objects.create(
            title=request.POST.get("title"),
            content=request.POST.get("content"),
        )
        return redirect('board:detail', article.pk)
    else:
        return render(request, 'board/create.html')

# 게시글 상세보기 함수
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = Comment.objects.filter(article=article)
    context = {
            "article" : article,
            "comments" : comments
        }
    if request.session.get("comment_pk"):
        context["comment_pk"] = request.session.get("comment_pk")
    return render(request, 'board/detail.html', context)

# 게시글 수정하기 함수
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
            "article" : article
        }
    if request.method == "POST":
        article.title = request.POST.get("title")
        article.content = request.POST.get("content")
        article.save()
        return redirect('board:detail', article_pk)
    else:
        return render(request, 'board/update.html', context)

# 게시글 삭제하기 함수
def delete(request, article_pk):
    Article.objects.get(pk=article_pk).delete()
    return redirect('board:index')

# 게시글에 달릴 댓글 작성하기 함수
def comment_create(request, article_pk):
    comment = Comment.objects.create(
        content = request.POST.get('content'),
        article = Article.objects.get(pk=article_pk)
    )
    return redirect('board:detail', article_pk)

# 게시글에 달린 댓글 삭제하기 함수
# urls에서 파라미터가 두 개이기 때문에 article_pk와 comment_pk 가 모두 필요하다.
def comment_delete(request, article_pk, comment_pk):
    Comment.objects.get(pk=comment_pk).delete()
    return redirect('board:detail', article_pk)

# 게시글에 달린 댓글 수정하기 함수
def comment_update(request, article_pk, comment_pk):
    if request.method == "POST":
        # Comment.objects.filter(pk=comment_pk).update(content=request.POST.get("updatedcontent"))
        comment = Comment.objects.get(pk=comment_pk)
        comment.content = request.POST.get("updatedcontent")
        comment.article = Article.objects.get(pk=article_pk)
        comment.save()
        del request.session["comment_pk"]
        return redirect('board:detail', article_pk)
    else:
        request.session["comment_pk"] = comment_pk
        return detail(request, article_pk)

Comment_Crud/BOARDEASY/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>board</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>

Comment_Crud/board/templates/board/create.html
{% extends 'base.html' %}

{% block body %}

<h1>새 글 쓰기</h1>

<form action="{% url 'board:create' %}" method=POST>
  {% csrf_token %}
  <p>제목 : <input type="text" name="title" placeholder="제목을 입력해주세요."></p>
  <p>내용 : <textarea name="content" cols="30" rows="10" placeholder="내용을 입력해주세요."></textarea></p>
  <input type="submit">
</form>

{% endblock %}

Comment_Crud/board/templates/board/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>글 상세 보기</h1>

<p>제목 : {{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
<p>최초 작성 : {{ article.created_at }} | 수정 : {{ article.updated_at }}</p>

<p><a href="{% url 'board:update' article.pk %}">[수정하기]</a> | <a href="{% url 'board:delete' article.pk %}">[삭제하기]</a></p>

<p><a href="{% url 'board:index' %}">작성한 글 모아보기</a></p>


<h2>댓글 달기</h2>
<form action="{% url 'board:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  <textarea name="content" cols="30" rows="5" placeholder="댓글내용을 입력해주세요"></textarea>
  <input type="submit">
</form>

<h2>모든 댓글 보기</h2>
<ul>
  {% for comment in comments %}
  <li>
    {% if comment.pk == comment_pk %}
    <form action="{% url 'board:comment_update' article.pk comment.pk %}" method="POST">
      {% csrf_token %}
      <textarea name="updatedcontent" cols="30" rows="5">{{ comment.content }}</textarea>
      <input type="submit">
    </form>
    {% else %}
    <p>{{ comment.content }}</p>
    <p>
      <a href="{% url 'board:comment_delete' article.pk comment.pk %}">[댓글 삭제하기]</a> | 
      <a href="{% url 'board:comment_update' article.pk comment.pk %}">[댓글 수정하기]</a>
    </p>
    {% endif %}
  </li>
  {% endfor %}
</ul>


{% endblock %}

Comment_Crud/board/templates/board/index.html
{% extends 'base.html' %}

{% block body %}

<h1>내가 쓴 글 모아보기</h1>

<ul>
{% for article in articles %}
  <li><a href="{% url 'board:detail' article.pk %}">{{ article.title }}</a></li>
{% endfor %}
</ul>

<a href="{% url 'board:create' %}">새 글 작성하기</a>

{% endblock %}

Comment_Crud/board/templates/board/update.html
{% extends 'base.html' %}

{% block body %}

<h1>글 고치기</h1>

<form action="{% url 'board:update' article.pk %}" method=POST>
  {% csrf_token %}
  <p>제목 : <input type="text" name="title" placeholder="{{ article.title }}"></p>
  <p>내용 : <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea></p>
  <input type="submit">
</form>

{% endblock %}