ModelForm_Crud - 복사본/ModelForm_Crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

ModelForm_Crud - 복사본/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password_change, name='password_change'),
]

ModelForm_Crud - 복사본/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/update/', views.update, name="update"),
    path('<int:article_pk>/like/', views.like, name='like'),
]

ModelForm_Crud - 복사본/accounts/models.py
from django.db import models

# Create your models here.

ModelForm_Crud - 복사본/blog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    users = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)

    class Meta:
        ordering = ('-pk',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={"pk":self.pk})

ModelForm_Crud - 복사본/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name', 'username',)

ModelForm_Crud - 복사본/blog/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content',]
    
    # options
    title = forms.CharField(
        max_length=50,
        label="제목",
        help_text="50자 이내로 작성해주세요",
        widget=forms.TextInput(
            attrs={
                "class" : "form-control",
                "placeholder" : "제목을 입력해주세요."
            }
        )
    )
    
    content = forms.CharField(
        label="내용",
        widget=forms.Textarea(
            attrs={
                "class" : "form-control",
                "placeholder" : "내용을 입력해주세요."
            }
        )
    )

ModelForm_Crud - 복사본/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
# Create your views here.

def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/auth_form.html', context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('blog:index')
    form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/auth_form.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('blog:index')

@require_POST
def delete(request):
    request.user.delete()
    return redirect('blog:index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/auth_form.html', context)

def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('blog:index')
    
    form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/auth_form.html', context)

ModelForm_Crud - 복사본/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.views.decorators.http import require_POST 
# Create your views here.


def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    return render(request, 'blog/index.html', context)

def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    context={
        "form" : ArticleForm(),
    }
    return render(request, 'blog/create.html', context)

def detail(request, pk):
    context = {
        "article" : get_object_or_404(Article, pk=pk)
    } 
    return render(request, 'blog/detail.html', context)

@require_POST
def delete(request, pk):
    if request.method == "POST":
        Article.objects.get(pk=pk).delete()
    return redirect('blog:index')

# 주의
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect(article)
    
    form = ArticleForm(instance=article)
    context = {
        "form" : form,
        "article" : article,
    }
    return render(request, 'blog/update.html', context)


def like(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    user = request.user
    if article.like_users.filter(pk=user.pk).exists():
        article.like_user.remove(user)
    else:
        article.like_user.add(user)

    return redirect(article)

ModelForm_Crud - 복사본/accounts/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
<h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
<h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
<h1>회원정보수정</h1>
{% else %}
<h1>비밀번호수정</h1>
{% endif %}

<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit="제출"%}{% endbuttons%}
</form>

{% endblock %}

ModelForm_Crud - 복사본/blog/templates/blog/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<form action="{% url 'blog:create' %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit">
</form>

{% endblock %}

ModelForm_Crud - 복사본/blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block body %}

<p>제목 : {{ article }}</p>
<p>내용 : {{ article.content }}</p>

<p><a href="{% url 'blog:index' %}">모든 게시글 보기</a></p>

{% if article.user == request.user %}
<p><a href="{% url 'blog:update' article.pk %}">수정하기</a> | 
  <form action="{% url 'blog:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제하기">
  </form>
</p>
{% endif %}

<p>좋아요 : {{ article.like_users.count }}</p>
{% with likers=article.like_users.all %}
<p>좋아요 목록:
  {% for liker in likers.all %}
    {{ liker }}
  {% endfor %}
</p>
  {% if user in likers %}
  <a href="{% url 'articles:like' article.pk %}">좋아요취소</a>
  {% else %}
  <a href="{% url 'articles:like' article.pk %}">좋아요</a>
  {% endif %}
  {% endwith %}
{% endblock %}

ModelForm_Crud - 복사본/blog/templates/blog/index.html
{% extends 'base.html' %}

{% block body %}

<h1>게시글 모아보기</h1>

{% if request.user.is_authenticated %}
<p><a href="{% url 'blog:create' %}">새 글쓰기</a></p>
{% endif %}

<ul>
  {% for article in articles %}
  <li><a href="{{ article.get_absolute_url }}">{{ article }}</a></li>
  {% endfor %}
</ul>



{% endblock %}

ModelForm_Crud - 복사본/blog/templates/blog/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<form action="{% url 'blog:update' article.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="수정하기">
</form>

{% endblock %}